# Generated by Django 5.2.15 on 2026-07-20 19:36

import django.db.models.deletion
import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', dlux.fields.MappedCharField(max_length=2000)),
                ('title', dlux.fields.MappedCharField(max_length=2000)),
                ('description', dlux.fields.MappedCharField(blank=True, max_length=2000)),
                ('resource_type', dlux.fields.MappedCharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')], max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', dlux.fields.MappedCharField(max_length=2000)),
                ('title', dlux.fields.MappedCharField(max_length=2000)),
                ('description', dlux.fields.MappedCharField(blank=True, max_length=2000)),
                ('resource_type', dlux.fields.MappedCharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')], max_length=2000)),
                ('collection', dlux.fields.MappedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dlux.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
