# Generated by Django 5.2.15 on 2026-07-16 19:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', models.CharField(max_length=2000, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('resource_type', models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', models.CharField(max_length=2000, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('resource_type', models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')], max_length=250)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='dlux.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ChildWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', models.CharField(max_length=2000, unique=True)),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('resource_type', models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')], max_length=250)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_works', to='dlux.work')),
            ],
        ),
    ]
