# Generated by Django 5.2.15 on 2026-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='childwork',
            constraint=models.UniqueConstraint(fields=('parent', 'order'), name='childwork_unique_order_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('ark',), name='dlux_collection_test_constraint'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('ark',), name='dlux_work_test_constraint'),
        ),
    ]
