# Generated by Django 5.2.15 on 2026-08-04 22:24

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childwork',
            name='resource_type',
            field=dlux.fields.ArrayField(base_field=models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collection',
            name='resource_type',
            field=dlux.fields.ArrayField(base_field=models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='work',
            name='resource_type',
            field=dlux.fields.ArrayField(base_field=models.CharField(choices=[('http://id.loc.gov/vocabulary/resourceTypes/car', 'cartographic'), ('http://id.loc.gov/vocabulary/resourceTypes/col', 'collection'), ('http://id.loc.gov/vocabulary/resourceTypes/mix', 'mixed material'), ('http://id.loc.gov/vocabulary/resourceTypes/mov', 'moving image'), ('http://id.loc.gov/vocabulary/resourceTypes/not', 'notated music'), ('http://id.loc.gov/vocabulary/resourceTypes/aud', 'sound recording'), ('http://id.loc.gov/vocabulary/resourceTypes/aum', 'sound recording-musical'), ('http://id.loc.gov/vocabulary/resourceTypes/aun', 'sound recording-nonmusical'), ('http://id.loc.gov/vocabulary/resourceTypes/img', 'still image'), ('http://id.loc.gov/vocabulary/resourceTypes/txt', 'text'), ('http://id.loc.gov/vocabulary/resourceTypes/art', 'three dimensional object')]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='childwork',
            name='ark',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='childwork',
            name='description',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='childwork',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='ark',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='ark',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(),
        ),
    ]
