# Generated by Django 5.2.15 on 2026-08-26 23:06

import django.core.validators
import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0004_remove_work_collection_record_delete_childwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='normalized_date',
            field=dlux.fields.ArrayField(base_field=models.TextField(help_text='Single date (e.g. 1980, 2020-05, 2020-05-15)or range (e.g 1980-01-04/1981-01-04). Supports 3-digit (but not fewer) and negative years (e.g. 750 or -2000).', validators=[django.core.validators.RegexValidator(message='Date must be in format YYYY, YYYY-MM, YYYY-MM-DD, or START_DATE/END_DATE. Supports 3-digit (but not fewer) and negative years, e.g. 750 or -2000.', regex='^-?\\d?\\d\\d\\d(-\\d\\d){0,2}(/-?\\d?\\d\\d\\d(-\\d\\d){0,2})?$')]), blank=True, default=list, size=None),
        ),
    ]
