# Generated by Django 5.2.15 on 2026-08-26 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0005_record_date_created_record_normalized_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='access_copy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='iiif_manifest_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='iiif_viewing_hint',
            field=models.CharField(blank=True, choices=[('http://iiif.io/api/presentation/2#pagedHint', 'paged'), ('http://iiif.io/api/presentation/2#individualsHint', 'individuals'), ('http://iiif.io/api/presentation/2#continuousHint', 'continuous'), ('http://iiif.io/api/presentation/2#nonPagedHint', 'non-paged'), ('http://iiif.io/api/presentation/2#facingPagesHint', 'facing-pages'), ('http://iiif.io/api/presentation/2#multiPartHint', 'multi-part')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='preservation_copy',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Preservation copy must be a path starting with 'Masters/' followed by one of the following subfolders: dlmasters, CDLI Masters, Livingstone, Maps, MEAP, or othermasters.", regex='^Masters/(dlmasters|CDLIMasters|Livingstone|Maps|MEAP|othermasters)/.*')]),
        ),
        migrations.AddField(
            model_name='record',
            name='thumbnail_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
