# Generated by Django 5.2.15 on 2026-08-28 19:06

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0006_record_access_copy_record_iiif_manifest_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='archival_collection_box',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='archival_collection_folder',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='archival_collection_number',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='archival_collection_title',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='finding_aid_url',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='Finding aid URL'),
        ),
        migrations.AddField(
            model_name='record',
            name='funding_note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='local_identifier',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='local_rights_statement',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='opac_url',
            field=models.CharField(blank=True, verbose_name='OPAC URL'),
        ),
        migrations.AddField(
            model_name='record',
            name='program',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='repository',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='rights_country',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='rights_statement',
            field=dlux.fields.ArrayField(base_field=models.TextField(choices=[('http://vocabs.library.ucla.edu/rights/copyrighted', 'copyrighted'), ('http://vocabs.library.ucla.edu/rights/unknown', 'unknown'), ('http://vocabs.library.ucla.edu/rights/publicDomain', 'public domain')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='services_contact',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
