# Generated by Django 5.2.15 on 2026-09-09 18:14

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0007_record_archival_collection_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dimensions',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='extent',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
