# Generated by Django 5.2.15 on 2026-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0008_record_dimensions_record_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='latitude',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='longitude',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='subject_geographic',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
