# Generated by Django 5.2.15 on 2026-09-18 00:12

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0008_record_dimensions_record_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='latitude',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='longitude',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='subject_geographic',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
