# Generated by Django 5.2.15 on 2026-10-01 17:05

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0010_record_alternative_title_record_architect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='binding_condition',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='binding_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='record',
            name='collation',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='condition_note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='folio_dimensions',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='form',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='format_book',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='medium',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='page_layout',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='shelfmark',
            field=models.CharField(blank=True, default=''),
        ),
    ]
