# Generated by Django 5.2.15 on 2026-10-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0011_record_binding_condition_record_binding_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='shelfmark',
            field=models.CharField(blank=True),
        ),
    ]
