# Generated by Django 5.2.15 on 2026-10-02 21:44

import dlux.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0012_alter_record_shelfmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='citation_source',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='content_disclaimer',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='contents',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='contents_note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='delivery',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='electronic_locator',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='explicit',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='featured_image',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='features',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='foliation',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='hand_note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='history',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='host',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='identifier',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='iiif_range',
            field=models.CharField(blank=True, verbose_name='IIIF range'),
        ),
        migrations.AddField(
            model_name='record',
            name='iiif_text_direction',
            field=models.CharField(blank=True, choices=[('http://iiif.io/api/presentation/2#leftToRightDirection', 'left-to-right'), ('http://iiif.io/api/presentation/2#rightToLeftDirection', 'right-to-left'), ('http://iiif.io/api/presentation/2#topToBottomDirection', 'top-to-bottom'), ('http://iiif.io/api/presentation/2#bottomToTopDirection', 'bottom-to-top')], verbose_name='IIIF text direction'),
        ),
        migrations.AddField(
            model_name='record',
            name='illustrations_note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='image_count',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='incipit',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='license',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='masthead_parameters',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='note_admin',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='oai_set',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='OAI set'),
        ),
        migrations.AddField(
            model_name='record',
            name='other_versions',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='Other versions'),
        ),
        migrations.AddField(
            model_name='record',
            name='related_record',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='related_to',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='representative_image',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='resp_statement',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='support',
            field=dlux.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='record',
            name='tagline',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='visibility',
            field=models.CharField(blank=True, choices=[('authenticated', 'authenticated'), ('open', 'open'), ('ucla', 'ucla')]),
        ),
    ]
